import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CourseProvider } from "./Context/CourseContext";
import { getCookie } from "cookies-next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const token = getCookie("accessToken");
  const email =  getCookie("email");
  const role =  getCookie("role");

  console.log({token, email, role})
  return (
    <html lang="en" data-theme="winter" className="">
      <body
        className={`${inter.className} min-h-screen bg-gradient-to-r from-custom-white via-custom-gray-light to-custom-gray text-black`}
      >
        <CourseProvider>
          <Navbar />
          {children}
          <Footer />
        </CourseProvider>
      </body>
    </html>
  );
}
